name: Build Flutter

on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v*" # Runs only when a version tag (e.g., v1.0.0) is pushed
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual execution

jobs:
  build:
    uses: OpenMediaStation/Pipelines/.github/workflows/build-flutter.yaml@main
    with:
      # flutter-version: "3.29.0"
      flatpak-name: "org.openmediastation.book"
      app-name: "open_media_station_book"
    secrets:
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      CERTIFICATE_P12: ${{ secrets.CERTIFICATE_P12 }}
      PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
      APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}